name: woohakdong
description: "[2024-2 SW 캡스톤디자인] 모바일 개발 레포지토리"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  gap: ^3.0.1
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  flutter_screenutil: ^5.9.3
  shared_preferences: ^2.3.2
  flutter_native_splash: ^2.4.1
  google_sign_in: ^6.2.1
  flutter_secure_storage: ^9.2.2
  logger: ^2.4.0
  http: ^1.2.2
  flutter_dotenv: ^5.1.0
  dio: ^5.7.0
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  currency_text_input_formatter: ^2.2.5
  intl: ^0.19.0
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  mime: ^1.0.6
  currency_formatter: ^2.2.1
  http_parser: ^4.0.2
  path_provider: ^2.1.4
  qr_flutter: ^4.1.0
  fluttertoast: ^8.2.8
  font_awesome_flutter: ^10.7.0
  material_symbols_icons: ^4.2789.0
  cached_network_image: ^3.4.1
  sentry_flutter: ^8.9.0
  photo_view: ^0.15.0
  skeletonizer: ^1.4.2
  app_settings: ^5.1.1
  syncfusion_flutter_datepicker: ^27.1.58
  table_calendar: ^3.1.2
  board_datetime_picker: ^2.1.5
  url_launcher: ^6.3.1
  tap_debouncer: ^2.2.0
  package_info_plus: ^8.1.1
  loading_animation_widget: ^1.3.0
  flutter_phoenix: ^1.1.1
  animated_toggle_switch: ^0.8.3
  file_picker: ^8.1.4
  image_gallery_saver_plus: ^3.0.5
  mask_text_input_formatter: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_oss_licenses: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/logos/google.png
    - assets/images/club/club_basic_image.jpg
    - assets/images/item/item_digital_basic_image.jpg
    - assets/images/item/item_sport_basic_image.jpg
    - assets/images/item/item_book_basic_image.jpg
    - assets/images/item/item_clothes_basic_image.jpg
    - assets/images/item/item_stationery_basic_image.jpg
    - assets/images/item/item_etc_basic_image.jpg

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/pretendard/Pretendard-Regular.ttf
          weight: 400
        - asset: assets/fonts/pretendard/Pretendard-SemiBold.ttf
          weight: 600


