name: woohakdong
description: "[2024-2 SW 캡스톤디자인] 모바일 개발 레포지토리"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  gap: ^3.0.1
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  flutter_screenutil: ^5.9.3
  shared_preferences: ^2.3.2
  flutter_native_splash: ^2.4.1
  google_sign_in: ^6.2.1
  flutter_secure_storage: ^9.2.2
  logger: ^2.4.0
  http: ^1.2.2
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/logos/google.png

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/pretendard/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/pretendard/Pretendard-SemiBold.otf
          weight: 600


