default_platform(:android)

platform :android do
  desc "Firebase App Distribution Android 배포"
  lane :deploy_android do
    # 앱 빌드
    sh("flutter build apk --release --target-platform=android-arm64")

    # Firebase 배포
    firebase_app_distribution(
      app: ENV["FIREBASE_ANDROID_APP_ID"],
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
      groups: "team8901",
      release_notes: "Firebase App Distribution 배포 테스트",
      android_artifact_type: "APK",
      apk_path: ENV["RELEASE_APK_PATH"]
    )
  end
end
