## Firebase App Distribution에 업로드는 성공하지만, 앱 실행 후 스플래쉬 화면으로 넘어가지 않음
## 아마 Firebase 초기화와 관련해서 문제가 있는 것 같음

name: Firebase App Distribution

on:
  push:
    branches:
      - WHD-283_cicd-try_test_cicd_for_firebase_app_distribution
  pull_request:
    branches:
      - WHD-283_cicd-try_test_cicd_for_firebase_app_distribution
  workflow_dispatch:

jobs:
  build:
    name: Firebase App Distribution
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Java 환경 설정
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Flutter 환경 설정
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.1'
          channel: 'stable'

      - name: KeyStore 생성
        id: android_keystore
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: key.jks
          fileDir: android/app
          encodedString: ${{ secrets.KEY_JKS_BASE64 }}

      - name: Key Properties 생성
        run: echo "${{ secrets.KEY_PROPERTIES }}" > android/key.properties

      - name: Firebase 및 환경 설정 파일 생성
        run: |
          # Firebase 설정 파일
          echo '${{ secrets.FIREBASE_JSON }}' > firebase.json
          echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > android/app/google-services.json    
          
          # 환경 변수 설정
          echo "V1_SERVER_BASE_URL=${{ secrets.V1_SERVER_BASE_URL }}" > .env
          echo "SENTRY_DSN=${{ secrets.SENTRY_DSN }}" >> .env
          echo "FIREBASE_MESSAGING_SENDER_ID=${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}" >> .env
          echo "FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}" >> .env
          echo "FIREBASE_STORAGE_BUCKET=${{ secrets.FIREBASE_STORAGE_BUCKET }}" >> .env
          echo "FIREBASE_ANDROID_APP_KEY=${{ secrets.FIREBASE_ANDROID_APP_KEY }}" >> .env
          echo "FIREBASE_ANDROID_APP_ID=${{ secrets.FIREBASE_ANDROID_APP_ID }}" >> .env
          echo "FIREBASE_IOS_APP_KEY=${{ secrets.FIREBASE_IOS_APP_KEY }}" >> .env
          echo "FIREBASE_IOS_APP_ID=${{ secrets.FIREBASE_IOS_APP_ID }}" >> .env
          echo "FIREBASE_ANDROID_CLIENT_ID=${{ secrets.FIREBASE_ANDROID_CLIENT_ID }}" >> .env
          echo "FIREBASE_IOS_CLIENT_ID=${{ secrets.FIREBASE_IOS_CLIENT_ID }}" >> .env
          echo "FIREBASE_IOS_BUNDLE_ID=${{ secrets.FIREBASE_IOS_BUNDLE_ID }}" >> .env

      - name: 의존성 설치
        run: flutter pub get

      - name: APK 빌드
        run: flutter build apk --release --target-platform=android-arm64

      - name: Firebase App Distribution에 업로드
        uses: wzieba/Firebase-Distribution-Github-Action@v1.7.0
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_CREDENTIAL_FILE_CONTENT }}
          groups: team8901
          file: build/app/outputs/flutter-apk/app-release.apk
